#!/bin/sh

PATH=/usr/bin:/usr/sbin

. /etc/runit/core-services/lib

[ -r /etc/rc.conf ] && . /etc/rc.conf

echo
log "Waiting for services to stop..."
sv force-stop /var/service/*
sv exit /var/service/*

[ -x /etc/rc.shutdown ] && /etc/rc.shutdown

if [ -a -n "$HARDWARECLOCK" ]; then
	hwclock --systohc ${HARDWARECLOCK:+--$(echo $HARDWARECLOCK | tr A-Z a-z)}
fi

log "Sending TERM signal to processes..."; {
	kall 15
	sleep 2
}

log "Sending KILL signal to all processes..."; {
	kall 9
}

log "Unmounting filesystems and disabling swap..."; {
	swapoff -a
	umount -rat nosysfs,proc,devtmpfs,tmpfs
}

log "Remounting rootfs as read-only"; {
	mount -o remount,ro /
	sync
}



